os: linux
dist: xenial

language: python
python: 3.8
cache: pip

jobs:
  include:
    - name: "Test"
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
